backend:
  name: git-gateway
  branch: Test

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "scouts"
    label: "Scouts Page"
    files:
      - file: "content/scouts.json"
        label: "Scouts Page Content"
        name: "scouts"
        fields:
          - { label: "Page Title", name: "page_title", widget: "string" }
          - { label: "Intro Text", name: "intro_text", widget: "text" }
